#!/bin/bash -x
module="scargle_fastc"
# Purpose: Build command for this module
#  Author: Kenneth Mighell
# Version: 0.3.1  2018MAY05
mkdir .old
mv $module.so .old/
python setup_$module.py build_ext --inplace
#EOF
